/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import Control.*;
import Exception.*;

/**
 *
 * @author Andreas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ControllerUser c;
    public String username;
    public String password;

    public Login() {
        c = new ControllerUser();
        initComponents();
        this.setLocation(500, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        labelketikUser = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        labelketikPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Perpustakaan PBO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Semangat membara dalam baca ......");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama User :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kata Sandi :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 500, -1, -1));

        btnLogin.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 610, 130, 50));

        labelketikUser.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        labelketikUser.setText("Ketikkan nama user disini....");
        getContentPane().add(labelketikUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 460, -1, -1));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 450, 270, 40));

        labelketikPassword.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        labelketikPassword.setText("Ketikkan kata sandi disini....");
        getContentPane().add(labelketikPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 550, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 540, 260, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/loginbig.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cekKosong() throws exDataKosong {
        if (txtUsername.getText().equalsIgnoreCase("") || txtPassword.getText().equalsIgnoreCase("")) {
            throw new exDataKosong();
        }
    }

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {
        labelketikUser.setVisible(false);
        if ("".equalsIgnoreCase(txtPassword.getText())) {
            labelketikPassword.setVisible(true);
        }
        if ("".equalsIgnoreCase(txtUsername.getText())) {
            labelketikUser.setVisible(true);
        }
    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try {
            cekKosong();
            if (c.cekLogin(txtPassword.getText(), txtUsername.getText())) {
                username = txtUsername.getText();
                password = txtPassword.getText();
                if (txtUsername.getText().equals("admin")) {
                    FormAdmin formadmin = new FormAdmin();
                    FormBuku formbuku = new FormBuku();
                    formbuku.show();
                    //formadmin.show();
                    //formadmin.parseUserPass(username, password);
                    this.dispose();
                } else if (txtUsername.getText().equals("peminjam")) {
                    FormPengguna formpengguna = new FormPengguna();
                    formpengguna.show();
                    this.dispose();
                }
            }
            else
                JOptionPane.showMessageDialog(this, "Password atau Username salah!");
        } catch (exDataKosong e) {
            JOptionPane.showMessageDialog(this, e.getErorrMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelketikPassword;
    private javax.swing.JLabel labelketikUser;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
